version: '3'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./server/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  php:
    build: ./server/docker/php
    container_name: "laravel-php"
    ports:
      - "9000"
    volumes:
      - ./:/var/www
      - ./server/docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 13306:3306

  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports: 
      - 16379:6379