version: '3'
volumes:
  mysql-data:
    driver: local

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./server/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  php:
    build: ./server/docker/php
    container_name: "laravel-php"
    ports:
      - "9000"
    volumes:
      - ./:/var/www
      - ./server/docker/php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    restart: always
    image: postgres:alpine
    container_name: "laravel-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports: 
      - 16379:6379
